service: motos-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: false
      accessKeyId: fake
      secretAccessKey: fake
      region: us-east-1

functions:
  createParte:
    handler: src/functions/createParte.handler
    events:
      - http:
          path: partes
          method: post

  getPartes:
    handler: src/functions/getPartes.handler
    events:
      - http:
          path: partes
          method: get

resources:
  Resources:
    PartesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Partes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
          