service: motos-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

plugins:
  - serverless-offline

functions:
  createParte:
    handler: src/functions/createParte.handler
    events:
      - http:
          path: partes
          method: post

  getPartes:
    handler: src/functions/getPartes.handler
    events:
      - http:
          path: partes
          method: get
          